apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-deploy
spec:
  resources:
    - name: docker-source
      type: git
    - name: builtImage
      type: image
  params:
  tasks:
    - name: build-image
      taskRef:
        name: build-docker-image-from-git
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/docker-source
      resources:
        inputs:
          - name: docker-source
            resource: docker-source
        outputs:
          - name: builtImage
            resource: builtImage
    - name: deploy-image
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: docker-source
          - name: image
            resource: builtImage
            from:
              - build-image
      params:
        - name: path
          value: /workspace/source/k8s_manifest/deploy.yaml
