apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: test-cat-deploy
      image: lachlanevenson/k8s-kubectl
      command: ["cat"]
      args:
        - "$(params.path)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.path)"
